build:
  maxIssues: 0
  weights:
    complexity: 2
    formatting: 1
    LongParameterList: 1
    style: 1

config:
  validation: true
  warningsAsErrors: false
  checkExhaustiveness: false

complexity:
  TooManyFunctions:
    active: false
  LargeClass:
    active: true
    threshold: 200
  LongMethod:
    active: true
    threshold: 20
  NestedBlockDepth:
    active: true
    threshold: 2

style:
  MaxLineLength:
    active: true
    maxLineLength: 120
  ReturnCount:
    active: true
    max: 2
  ForbiddenVoid:
    active: true
  OptionalAbstractKeyword:
    active: true
  ExpressionBodySyntax:
    active: true

naming:
  PackageNaming:
    active: false
  FunctionNaming:
    active: false

formatting:
  active: true
  SpacingAroundOperators:
    active: true
  SpacingAroundCurlyBraces:
    active: true
  SpacingAroundParens:
    active: true
  SpacingAroundCommas:
    active: true
  RedundantVisibilityModifier:
    active: true
  NoWildcardImports:
    active: true